import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../ShopComponents/Header";
import Footer from "../ShopComponents/Footer";
import { Suspense } from "react";
import Loader from "../Loader";
import { ToastContainer } from "react-toastify";
import Providers from "./redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="px-40">
            <Providers>
              <Suspense fallback={<Loader />}>{children}</Suspense>
            </Providers>
        </main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
