import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/crm/crm_component/layout_style/sidebar";
import { ToastContainer } from "react-toastify";
import { limitedAdminInfo } from "@/helperFunction/getAdminInfo";
import "../../globals.css";
import { Suspense } from "react";
import Loader from "@/app/Loader";
import Providers from "../redux/Providers";
import ClientLayout from "../crm_component/layout_style/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function CrmLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const adminInfo = await limitedAdminInfo();

  if (!adminInfo) {
    throw new Error("User not found or not logged in");
  }
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  py-5`}
      >
        <SidebarProvider defaultOpen={true}>
          <Suspense fallback={<Loader />}>
            <div className="grid min-h-screen w-full md:grid-cols-[auto_1fr]">
              <AppSidebar />
              <div className="flex flex-col">
                <Providers>
                  <ClientLayout adminInfo={adminInfo}>{children}</ClientLayout>
                </Providers>
              </div>
            </div>
          </Suspense>
        </SidebarProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
