import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/crm/crm_component/layout_style/sidebar";
import { Header } from "@/app/crm/crm_component/layout_style/header";
import { ToastContainer } from "react-toastify";
import { AdminInfoProvider } from "@/hooks/crm/share-admin-context";
import { limitedAdminInfo } from "@/CrmGlobalData/shartLimitedAdminInfo";
import "../../globals.css";
import { Suspense } from "react";
import Loader from "@/app/Loader";
import Providers from "../redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CrmLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const adminInfo = await limitedAdminInfo();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  py-5`}
      >
        <AdminInfoProvider initialAdminInfo={adminInfo}>
              <SidebarProvider defaultOpen={true}>
                <Suspense fallback={<Loader />}>
                  <div className="grid min-h-screen w-full md:grid-cols-[auto_1fr]">
                    <AppSidebar />
                    <div className="flex flex-col">
                      <Providers>
                        <Header />
                        <main className="flex-1 p-4 md:p-6">{children}</main>
                      </Providers>
                    </div>
                  </div>
                </Suspense>
              </SidebarProvider>
              <ToastContainer />
        </AdminInfoProvider>
      </body>
    </html>
  );
}
